name: Go

on:
  - push

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: 
           go get -d ./...
           go mod vendor
      - name: Test
        run: go test ./...
